# baseURL = "http://bbq-elitre.netlify.app"
baseURL = "https://bbq.elitre.biz"
disableLanguages = ["fr,de,it"]
disqusShortname = ""
googleAnalytics = "G-P9BZFXHLEJ"
paginate = "4"
summaryLength = "30"
theme = "airspace-hugo"
title = "Elitre - BBQ Burner Grill & Governor AGA"

[languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 1996-2021 Elitre, All Rights Reserved."
languageCode = "en-US"
languageName = "English"
weight = 1

[[languages.en.menu.footer]]
URL = "about"
name = "About"
weight = 1
[[languages.en.menu.footer]]
URL = "project"
name = "Product"
weight = 2

#[[languages.en.menu.footer]]
#URL = "service"
#name = "Service"
#weight = 3

#[[languages.en.menu.footer]]
#URL = "pricing"
#name = "Pricing"
#weight = 4
[[languages.en.menu.footer]]
URL = "faq"
name = "FAQ"
weight = 5
[[languages.en.menu.footer]]
URL = "contact"
name = "Contact"
weight = 6
#menu bak
#[[languages.en.menu.main]]
#hasChildren = true
#name = "More"
#weight = 0

[[languages.en.menu.main]]
URL = ""
name = "Home"
weight = 1
[[languages.en.menu.main]]
URL = "about"
name = "About"
weight = 2
[[languages.en.menu.main]]
URL = "project"
name = "Product"
weight = 3
[[languages.en.menu.main]]
URL = "contact"
name = "Contact"
weight = 5
[[languages.en.menu.main]]
URL = "faq"
name = "FAQ"
weight = 4


# [[languages.en.menu.main]]
# URL = "More"
# name = "More"
# weight = 6
# [[languages.en.menu.main]]
# URL = "More1"
# name = "More1"
# parent = "More"
# weight = 1
# [[languages.en.menu.main]]
# URL = "More2"
# name = "More2"
# parent = "More"
# weight = 2






[markup.goldmark.renderer]
unsafe = true
[markup.tableOfContents]
endLevel = 6
ordered = false
startLevel = 2
[outputs]
home = ["HTML"]
[params]
author = "Elitre"
description = "Welcome to Elitre Co., Ltd, BBQ burners, BBQ Component, Gas hoses, Gas Hob component parts"
image = "images/logo.png"
logo = "images/logo.png"
logo_width = "150px"
[params.contact]
address_descriptors = true
email = "elitre@gmail.com"
#location = "**ELITRE**  \nNo.2, Nanshi 1st. Street  \nLinkou District, New Taipei City  \nTaiwan\n"
location = "No.2, Nanshi 1st. Street Linkou District, New Taipei City, Taiwan"
phone = "+886-2-2600-3383"

[params.contact.form]
action = "#"
enable = false
success_image = "images/paper-plane.svg"
use_netlify = true
[params.cookies]
enable = false
expire_days = 2
[params.counter]
enable = true
username = ""
[params.gmap]
enable = true
gmap_api = ""
map_latitude = "25.07504376813366"
map_longitude = "121.36069503206059"
map_marker = "images/marker.png"
#add aos css
[[params.plugins.css]]
attributes = "media='screen'"
link = "/plugins/aos/aos.css"
[[params.plugins.css]]
attributes = "media='screen'"
link = "plugins/bootstrap/css/bootstrap.min.css"
[[params.plugins.css]]
attributes = ""
link = "plugins/ionicons/css/ionicons.min.css"
[[params.plugins.css]]
attributes = ""
link = "plugins/magnific-popup/magnific-popup.min.css"
[[params.plugins.css]]
attributes = ""
link = "plugins/slick/slick.css"
[[params.plugins.js]]
attributes = ""
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
attributes = ""
link = "plugins/bootstrap/js/bootstrap.min.js"
[[params.plugins.js]]
attributes = ""
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
attributes = ""
link = "plugins/magnific-popup/magnific-popup.min.js"
#add lazyload https://github.com/tuupola/lazyload
[[params.plugins.js]]
attributes = ""
link = "plugins/lazyload/lazysizes.min.js"
[[params.plugins.js]]
attributes = ""
link = "plugins/shuffle/shuffle.min.js"

#[[params.plugins.js]]
#attributes = ""
#link = "plugins/imageloaded/imagesloaded.pkgd.min.js"
[[params.plugins.js]]
attributes = "defer"
link = "plugins/google-map/gmap.js"
#add aos js and css
[[params.plugins.js]]
attributes = ""
link = "plugins/aos/aos.js"

[params.preloader]
enable = false
preloader = "images/logo.png"
[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]
[[params.social]]
icon = "ion-social-googleplus-outline"
link = "#"
[[params.social]]
icon = "ion-social-linkedin-outline"
link = "#"
[[params.social]]
icon = "ion-social-pinterest-outline"
link = "#"
[[params.social]]
icon = "ion-social-dribbble-outline"
link = "#"
[[params.social]]
icon = "ion-social-twitter-outline"
link = "#"
[[params.social]]
icon = "ion-social-facebook-outline"
link = "#"
